---
title: "2.prelim_fluxviz"
author: "abbey yatsko"
date: "26/08/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(dplyr)
library(ggpubr)
```

## read in data 
```{r data load}
CO2_fluxfinal <- read.csv("/Users/abbeyyatsko/Desktop/repos/TMI_flux/data/finalfluxes/CO2_fluxfinalTMI.csv")
CH4_fluxfinal<- read.csv("/Users/abbeyyatsko/Desktop/repos/TMI_flux/data/finalfluxes/CH4_fluxfinalTMI.csv")
```

## merge in species data to flux data 
```{r}
species <- read.csv("/Users/abbeyyatsko/Desktop/repos/TMI_flux/data/finalfluxes/Abbey termites .xlsx - Sheet1.csv")
species <- species[c("X", "ID_cleaned")]

# merge sp and CH4flux_final, CO2_fluxfinal
species <- species %>%
  rename(sample = X)
CH4_fluxfinal <- merge(CH4_fluxfinal, species, by = c("sample")) 
CO2_fluxfinal <- merge(CO2_fluxfinal, species, by = c("sample")) 

# new column for methane:co2
# first need to convert CO2 from mmol to umol (in order to match CH4 in units of umol)
# (conversion factor 1000umol = 1mmol)
CO2_fluxfinal$flux.CO2_umol <- CO2_fluxfinal$flux.CO2*1000
CO2_fluxfinal <- CO2_fluxfinal %>% relocate(flux.CO2_umol, .after = flux.CO2)

CH4_fluxfinal$ch4_co2 <-  CH4_fluxfinal$flux.CH4/CO2_fluxfinal$flux.CO2
CH4_fluxfinal <- CH4_fluxfinal %>% relocate(ch4_co2, .after = flux.CH4)

# subset df to create just soils and just mounds (for later on. just to have df prepped)
soils <- CH4_fluxfinal[CH4_fluxfinal$flux_source == 's',]
mounds <- CH4_fluxfinal[CH4_fluxfinal$flux_source == 'm',]
```

## methane flux by individual mound
```{r flux}
# mounds all, colored by species
a1 <- ggplot(data = mounds, aes(x = as.factor(sample), y = flux.CH4, fill = ID_cleaned)) + 
  geom_boxplot()+ 
  geom_jitter()+
  theme_classic()+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
  ylab("CH4 flux umol/d/m2")+
  labs(title = "mound")

# soils all, colored by species
a2 <- ggplot(data = soils, aes(x = as.factor(sample), y = flux.CH4, fill = ID_cleaned)) + 
  geom_boxplot()+ 
  geom_jitter()+
  theme_classic()+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
  ylab("CH4 flux umol/d/m2")+
  labs(title = "soil")
ggarrange(a1, a2, ncol=1)

# same as above but with CH4:CO2
a3 <- ggplot(data = mounds, aes(x = as.factor(sample), y = ch4_co2, fill = ID_cleaned)) + 
  geom_boxplot()+ 
  theme_classic()+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
  ylim(0,50)+ # for outliers
  labs(title = "mound")
a4 <- ggplot(data = soils, aes(x = as.factor(sample), y = ch4_co2, fill = ID_cleaned)) + 
  geom_boxplot()+ 
  theme_classic()+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
  ylim(0,2.5)+ # for outliers
  labs(title = "soil")
ggarrange(a3, a4, ncol=1)
```

## methane flux by mound or soil measurement 
```{r by soil/mound}
b <- ggplot(data = CH4_fluxfinal, aes(x = as.factor(flux_source), y = flux.CH4)) + 
  geom_boxplot()+ 
  geom_jitter()+
  theme_light()
```

## methane flux by factor(position)
```{r by position}
c1 <- ggplot(data = CH4_fluxfinal, aes(x = as.factor(position), y = flux.CH4, fill = ID_cleaned)) + 
  geom_boxplot()+ 
  ylab("CH4 flux umol/d/m2")+
  theme_light()
c2 <- ggplot(data = CH4_fluxfinal, aes(x = as.factor(position), y = ch4_co2, fill = ID_cleaned)) + 
  geom_boxplot()+ 
  theme_light()

ggarrange(c1, c2, ncol = 1)
```

## methane flux for mounds only by factor(direction)
```{r by direction}
d1 <- ggplot(data = mounds, aes(x = as.factor(directon), y = flux.CH4, fill = flux_source)) + 
  geom_boxplot()+ 
  geom_jitter()+
  ylab("CH4 flux umol/d/m2")+
  theme_light()
d2 <- ggplot(data = mounds, aes(x = as.factor(directon), y = ch4_co2, fill = flux_source)) + 
  geom_boxplot()+ 
  geom_jitter()+
  theme_light()

ggarrange(d1, d2, ncol = 1)
```

## methane flux by factor(species)
```{r by species}
e <- ggplot(data = CH4_fluxfinal, aes(x = as.factor(ID_cleaned), y = flux.CH4, fill = flux_source)) + 
  geom_boxplot()+ 
  ylab("CH4 flux umol/d/m2")+
  theme_light()
```

## methane flux by methane:co2 
```{r}
 f <- ggplot(data = CH4_fluxfinal, aes(x = as.factor(ID_cleaned), y = ch4_co2, fill = flux_source)) + 
  geom_boxplot()+ 
  geom_jitter()+
  theme_light()+
  scale_y_continuous(limits = c(-1, 50))

ggarrange(e, f, ncol = 1)
```

## methane flux by species faceted with mound/soil and positioning
```{r}
g <- ggplot(data = CH4_fluxfinal, aes(x = as.factor(ID_cleaned), y = flux.CH4, fill = flux_source)) + 
  geom_boxplot()+ 
  geom_point(aes(col=position), position = "jitter")+
  ylab("CH4 flux umol/d/m2")+
  theme_light()
```




