---
title: "6. flux_compile"
author: "abbey yatsko"
date: "2024-03-15"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

libraries
```{r}

```

read in data
```{r data load}
may_CO2 <- read.csv("/Users/abbeyyatsko/Desktop/repos/TMI_flux/data/finalfluxes/CO2_fluxfinal_may22_fixed.csv")
may_CH4 <- read.csv("/Users/abbeyyatsko/Desktop/repos/TMI_flux/data/finalfluxes/CH4_fluxfinal_may22_fixed.csv")

nov_CO2 <- read.csv("/Users/abbeyyatsko/Desktop/repos/TMI_flux/data/finalfluxes/CO2_fluxfinal_nov22_fixed.csv")
nov_CH4 <- read.csv("/Users/abbeyyatsko/Desktop/repos/TMI_flux/data/finalfluxes/CH4_fluxfinal_nov22_fixed.csv")

aug_CO2 <- read.csv("/Users/abbeyyatsko/Desktop/repos/TMI_flux/data/finalfluxes/CO2_fluxfinal_aug23_fixed.csv")
aug_CH4 <- read.csv("/Users/abbeyyatsko/Desktop/repos/TMI_flux/data/finalfluxes/CH4_fluxfinal_aug23_fixed.csv")

feb_CO2 <- read.csv("/Users/abbeyyatsko/Desktop/repos/TMI_flux/data/finalfluxes/CO2_fluxfinal_feb24_fixed.csv")
feb_CH4 <- read.csv("/Users/abbeyyatsko/Desktop/repos/TMI_flux/data/finalfluxes/CH4_fluxfinal_feb24_fixed.csv")
```

data clean and reorganize
```{r}
# lists of CO2 and CH4 files from different seasons
CH4_all <- list(may_CH4, nov_CH4, aug_CH4, feb_CH4)
CO2_all <- list(may_CO2, nov_CO2, aug_CO2, feb_CO2)

# create new column for methane:co2
# for each element in list 
x <- data.frame(CO2_all[1])
y <- data.frame(CH4_all[1])

full_df <- function(x, y){
  # merge CO2 and CH4 df together 
  all <- full_join(x, y)

  # convert CO2 from mmol to umol (in order to match CH4 units, conversion factor 1000umol = 1mmol)
  all$flux.CO2_umol <- all$flux.CO2*1000
  all <- all %>% relocate(flux.CO2_umol, .after = flux.CO2)
  all <- all %>% relocate(flux.CH4, .after = flux.CO2_umol)
  all <- all %>% relocate(R2.CH4, .after = R2.CO2)
  all <- all %>% relocate(p.CH4, .after = p.CO2)
  
  # define column for ratio of CH4:CO2
  all$CH4_CO2 <-  all$flux.CH4/all$flux.CO2_umol
  all <- all %>% relocate(CH4_CO2, .after = flux.CH4)

}

out <- lapply(seq_along(CH4_all), function(x) full_df(CH4_all[[x]], CO2_all[[x]]))
all_fluxes <- do.call("rbind.fill", out)

# rename species with scientific names 
all_fluxes$species_s <- ifelse(all_fluxes$species == "Ami", "A. laurensis","")
all_fluxes$species_s <- ifelse(all_fluxes$species == "Nasuti", "N. magnus", all_fluxes$species_s)
all_fluxes$species_s <- ifelse(all_fluxes$species == "Copto", "C. acinaciformis", all_fluxes$species_s)

# filter out measurements without species recorded
all_fluxes <- all_fluxes %>%
  filter(species_s != "")

# EXPORT - all fluxes
# write.csv(all_fluxes, "/Users/abbeyyatsko/Desktop/repos/TMI_flux/data/finalfluxes/all_fluxes.csv")

# EXPORT - mound-only fluxes
all_fluxes_mound <- all_fluxes[all_fluxes$flux_source =="m",]
# write.csv(all_fluxes_mound, "/Users/abbeyyatsko/Desktop/repos/TMI_flux/data/finalfluxes/all_fluxes_mound.csv")

# EXPORT - soil-only fluxes
all_fluxes_soil <- all_fluxes[all_fluxes$flux_source =="s",]
# write.csv(all_fluxes_soil, "/Users/abbeyyatsko/Desktop/repos/TMI_flux/data/finalfluxes/all_fluxes_soil.csv")
```

## WORKING HERE ##
data summary from compiled list 
```{r}
# summary of how mounds were measured for each campaign
detach(package:plyr)
summary_counts <- all_fluxes %>%
  group_by(campaign, species_s) %>%
    summarise(unique_samples = n_distinct(sample))

# how many measurements were made for each mound in the resampling campaign (shoudl be 4 or 5)
# filter out those that are not revisited by the resampling campaigns 
targets1 <- unique(nov_CH4$sample)
targets2 <- unique(aug_CH4$sample)
targets3 <- unique(feb_CH4$sample)
targets <- union(targets1, targets2)
targets_fin <- union(targets, targets3)

all_fluxes_resample <- all_fluxes[all_fluxes$sample %in% targets_fin, ]

# create unique ID for mounds in different sampling periods
all_fluxes_resample$ID_mound <- paste(all_fluxes_resample$sample, all_fluxes_resample$campaign, sep = "-")

# measurements per mound 
measurements_per_mound <- aggregate(all_fluxes_resample$tag , by=list(all_fluxes_resample$ID_mound ), FUN=length)

# measurements across all 4 campaigns 
repeated_counts <- all_fluxes_resample %>%
  group_by(sample) %>%
    summarise(remeasurements = n_distinct(campaign), 
              species = unique(species_s))

# reorder levels of campaigns 
all_fluxes_resample$campaign <- factor(all_fluxes_resample$campaign, levels = c("may22", "aug23", "nov22", "feb24"))

# create working df for coarse mound averages 
mound_avg_flux <- all_fluxes_resample %>% group_by(ID_mound, sample, species_s) %>% 
  summarise(mean_mound_fluxCH4=mean(flux.CH4),
            mean_mound_fluxCO2=mean(flux.CO2_umol), 
            mean_mound_fluxCH4_CO2=mean(CH4_CO2), 
            campaign = campaign)
```
