---
title: "7.flux_viz"
author: "abbey yatsko"
date: "26/08/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(dplyr)
library(plyr)
library(ggpubr)
```

data load 
```{r}
# all fluxes
all_fluxes <- read.csv("/Users/abbeyyatsko/Desktop/repos/TMI_flux/data/finalfluxes/all_fluxes.csv")
# all fluxes - mound 
all_fluxes_mound <- read.csv("/Users/abbeyyatsko/Desktop/repos/TMI_flux/data/finalfluxes/all_fluxes_mound.csv")
# all fluxes - soil 
all_fluxes_soil <- read.csv("/Users/abbeyyatsko/Desktop/repos/TMI_flux/data/finalfluxes/all_fluxes_soil.csv")
# all fluxes - seasonal 
all_fluxes_seasonal <- read.csv("/Users/abbeyyatsko/Desktop/repos/TMI_flux/data/finalfluxes/all_fluxes_resample_reps.csv")
# all fluxes - daily 
all_fluxes_daily <- read.csv("/Users/abbeyyatsko/Desktop/repos/TMI_flux/data/finalfluxes/all_daily_fluxes.csv")
# all fluxes - mound average
all_fluxes_mound_avg <- read.csv("/Users/abbeyyatsko/Desktop/repos/TMI_flux/data/finalfluxes/all_fluxes_mound_avg.csv")
```

mound flux and species
```{r}
# overall CH4 flux from three different species
m1 <- ggplot(data = all_fluxes_mound, aes(x = species_s, y = flux.CH4, fill = species_s)) + 
  geom_boxplot()+ 
  scale_x_discrete(limits = c("N. magnus", "A. laurensis", "C. acinaciformis"))+  
  theme_classic()+
  ylim(0,28000) + # removes two outliers to make graph more readable
  ylab("CH4 flux umol/d/m2")+
  xlab("")

# overall CO2 flux from three different species
m2 <- ggplot(data = all_fluxes_mound, aes(x = species_s, y = flux.CO2, fill = species_s)) + 
  geom_boxplot()+ 
  scale_x_discrete(limits = c("N. magnus", "A. laurensis", "C. acinaciformis"))+  
  theme_classic()+
  ylab("CO2 flux mmol/d/m2")+
  xlab("")

# overall CH4:CO2 from three different species
m3 <- ggplot(data = all_fluxes_mound, aes(x = species_s, y = CH4_CO2, fill = species_s)) + 
  geom_boxplot()+ 
  scale_x_discrete(limits = c("N. magnus", "A. laurensis", "C. acinaciformis"))+  
  theme_classic()+
  ylab("CH4:CO2")+
  ylim(0,0.075)+ # removes big outlier
  xlab("")

ggarrange(m1,m2,m3, ncol = 3, common.legend = TRUE)

# table of averages by species
detach(package:plyr)
sp_avg <- all_fluxes_mound %>% group_by(species_s) %>% 
  summarize(mean_CH4flux = mean(flux.CH4), 
            mean_CO2flux = mean(flux.CO2), 
            sd_CH4flux = sd(flux.CH4), 
            sd_CO2flux = sd(flux.CO2))
  
# unit conversion umol/m2*d to ug/m2*d (final units for CH4)
# flux*(1/1000000)*(16.04)*(1000000) 
# molecular mass conversion to g, then conversion back to ug for comparison 
```

mound flux and season
```{r}
# reorder levels of campaigns 
all_fluxes_seasonal$campaign <- factor(all_fluxes_seasonal$campaign, levels = c("may22", "aug23", "nov22", "feb24"))

# select for mound data only
all_fluxes_seasonal_mound <- all_fluxes_seasonal[all_fluxes_seasonal$flux_source =="m",]

# CH4 flux 
s1 <- ggplot(data = all_fluxes_seasonal_mound, aes(x = species_s, y = flux.CH4, fill = campaign)) + 
  geom_boxplot()+ 
  scale_x_discrete(limits = c("N. magnus", "A. laurensis", "C. acinaciformis"))+  
  theme_classic()+
  ylim(0, 22186) + # removes negative outlier
  ylab("CH4 flux umol/d/m2")+
  xlab("")

# CO2 flux 
s2 <- ggplot(data = all_fluxes_seasonal_mound, aes(x = species_s, y = flux.CO2, fill = campaign)) + 
  geom_boxplot()+ 
  scale_x_discrete(limits = c("N. magnus", "A. laurensis", "C. acinaciformis"))+  
  theme_classic()+
  ylim(0,4833) + # removes negative outlier
  ylab("CO2 flux mmol/d/m2")+
  xlab("")

# overall CH4:CO2 from three different species
s3 <- ggplot(data = all_fluxes_mound, aes(x = species_s, y = CH4_CO2, fill = campaign)) + 
  geom_boxplot()+ 
  scale_x_discrete(limits = c("N. magnus", "A. laurensis", "C. acinaciformis"))+  
  theme_classic()+
  ylab("CH4:CO2")+
  ylim(0,0.06)+ # removes big outlier
  xlab("")

ggarrange(s1,s2,s3, ncol = 3, common.legend = TRUE)
```

mound flux and temperature
```{r}
# mound flux and temperature
t1 <- ggplot(all_fluxes_seasonal_mound, aes(x = avg_respT, y = flux.CH4, color = campaign))+
  geom_smooth(method = 'auto', se = TRUE)+
  ylab("CH4 flux umol/d/m2")+
  xlab("Average Mound Surface Temperature (C)")+
  theme_classic()

t2 <- ggplot(all_fluxes_seasonal_mound, aes(x = avg_respT, y = flux.CO2, color = campaign))+
  geom_smooth(method = 'auto', se = TRUE)+
  ylab("CO2 flux mmol/d/m2")+
  xlab("Average Mound Surface Temperature (C)")+
  theme_classic()

ggarrange(t1, t2, ncol = 1, common.legend = TRUE)

# mound flux and time of day with temperature included
t <- all_fluxes_seasonal_mound[all_fluxes_seasonal_mound$campaign %in% c("nov22", "aug23", "feb24"),]
t$flux_start <- strptime(t$flux_start, "%H:%M")

tt <- all_fluxes_seasonal_mound[all_fluxes_seasonal_mound$campaign %in% c("may22"),]
start <- nchar(tt$flux_start) - 7
tt$flux_start_test <- substring(tt$flux_start, start, nchar(tt$flux_start))
tt$flux_start <- strptime(tt$flux_start_test, "%H:%M")
tt <- tt[, -which(names(tt) == "flux_start_test")]

all_fluxes_seasonal_mound_withtime <- rbind(t, tt)

# temperature throughout the day by season
t3 <- ggplot(all_fluxes_seasonal_mound_withtime, aes(x = as.POSIXct(flux_start), y = avg_respT, color = campaign))+
  geom_jitter()+
  geom_smooth(method = 'loess', se = TRUE)+
  ylab("Average Mound Surface Temperature (C)")+
  xlab("Time of day")+
  theme_classic()

# temperature response of gas flux by season
t4 <- ggplot(all_fluxes_seasonal_mound_withtime, aes(x = avg_respT, y = flux.CH4, color = campaign))+
  geom_point()+
  geom_smooth(method = 'lm', se = FALSE)+
  ylab("CH4 flux umol/d/m2")+
  xlab("Average Mound Surface Temperature (C)")+
  theme_classic()+
  ylim(0,25000) # address negative outlier 

ggarrange(t3, t4, ncol = 1, common.legend = TRUE)

# table of averages by season
season_avg <- all_fluxes_seasonal_mound %>% group_by(species_s, campaign) %>% 
  summarize(mean_CH4flux = mean(flux.CH4), 
            mean_CO2flux = mean(flux.CO2), 
            sd_CH4flux = sd(flux.CH4), 
            sd_CO2flux = sd(flux.CO2))
```

mound flux and position in mound 
```{r}

```

mound flux and size
```{r}
# merge with mound SA
mound_SA <- read.csv("/Users/abbeyyatsko/Desktop/repos/TMI_flux/data/supp_data/mound_SA.csv")
mound_SA <- mound_SA[, c('sample', 'SA_m2', 'basal_area_m2')]
mound_SA <- mound_SA[!is.na(mound_SA$SA_m2),]
mound_avg_flux <- merge(mound_avg_flux, mound_SA, by = "sample" )

# calculate mound-level flux
mound_avg_flux$mound_CH4flux <- mound_avg_flux$mean_mound_fluxCH4 * mound_avg_flux$SA_m2
mound_avg_flux$mound_CO2flux <- mound_avg_flux$mean_mound_fluxCO2 * mound_avg_flux$SA_m2

# graph methane flux by mound size (surface/basal area interchangeable: SA_m2/basal_area_m2)
a1 <- ggplot(data = mound_avg_flux, aes(x = SA_m2, y = mean_mound_fluxCH4)) +
  geom_point()+ 
  geom_smooth(method = 'lm')+
  scale_color_brewer("Blues")+
  #facet_grid(~campaign, scales = "free_x")+ 
  theme_classic()+
  ylab("Total mound CH4 flux (umol/d/mound)") +
  xlab("Mound basal area (m2)")

# graph carbon dioxide flux by mound size 
a2 <- ggplot(data = mound_avg_flux, aes(x = basal_area_m2, y = mean_mound_fluxCO2)) +
  geom_point()+ 
  geom_smooth(method = 'lm')+
  scale_color_brewer("Blues")+
  facet_wrap(campaign~species_s, scales = "free_x")+ 
  theme_classic()+
  ylab("Total mound CO2 flux (mmol/d/mound)") +
  xlab("Mound basal area (m2)")

# graph CH4:CO2 flux by mound size 
a3 <- ggplot(data = mound_avg_flux, aes(x = basal_area_m2, y = mean_mound_fluxCH4_CO2)) +
  geom_point()+ 
  geom_smooth(method = 'lm')+
  scale_color_brewer("Blues")+
  facet_wrap(~species_s, scales = "free_x")+ 
  theme_classic()+
  ylab("Total mound CH4:CO2") +
  xlab("Mound basal area (m2)")

ggarrange(a1, a2, a3, ncol = 1)

# relationship between surface area and basal area (by species)
ggplot(data = mound_avg_flux, aes(x = SA_m2, y = basal_area_m2)) +
  geom_point()+ 
  geom_smooth(method = 'lm')+
  scale_color_brewer("Blues")+
  facet_wrap(~species_s, scales = "free_x")+ 
  theme_classic()+
  ylab("Mound basal area (m2)") +
  xlab("Mound surface area (m2)")

# preliminary models 
mod <- lm(mean_mound_fluxCH4 ~ SA_m2 + species_s, data = mound_avg_flux)
summary(mod)
check_model(mod)
ggpredict(mod, terms = c("SA_m2", "species_s")) %>% plot(add.data = TRUE)

#FACET BY SEASON? 
```

mound flux throughout the day
Preliminary visualization 
```{r}
# read in data 
# CO2 (units are mmol/day)
CO2_day <- read.csv("/Users/abbeyyatsko/Desktop/repos/TMI_flux/data/finalfluxes/CO2_fluxfinal_aug23_day_fixed.csv")

# CH4 (units are umol/day)
CH4_day <- read.csv("/Users/abbeyyatsko/Desktop/repos/TMI_flux/data/finalfluxes/CH4_fluxfinal_aug23_day_fixed")

# reorder time of day categorical variable 
desired_order <- c("morning", "midday", "afternoon", "night")

# Re-order the levels
CH4_day$time_of_day <- factor(as.character(CH4_day$time_of_day), levels=desired_order )
CO2_day$time_of_day <- factor(as.character(CO2_day$time_of_day), levels=desired_order )

# Re-order the data.frame
CH4_day <- CH4_day[order(CH4_day$time_of_day),]
CO2_day <- CO2_day[order(CO2_day$time_of_day),]
```

Diurnal signal
```{r}
d1 <- ggplot(CO2_day, aes(x = time_of_day, y = flux.CO2, fill = time_of_day))+
  geom_boxplot()+
  geom_point()+
  theme_classic()+
  theme(legend.position="none")+
  xlab("")+
  ylab("CO2 flux")

# with species split out
d2 <- ggplot(CO2_day, aes(x = time_of_day, y = flux.CO2, fill = time_of_day))+
  geom_boxplot()+
  geom_point()+
  theme_classic()+
  theme(legend.position="none")+
  xlab("")+
  ylab("CO2 flux")+
  facet_wrap(~species, scales = "free")+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

ggarrange(d1,d2)
```

Temperature signal 
```{r}
# temperature throughout daily cycle 
d3 <- ggplot(CH4_day, aes(x = avg_respT, y = flux.CH4))+
  geom_point()+
  geom_smooth()+
  theme_classic()+
  theme(legend.position="none")+ 
  xlab("Temperature (C)")+
  ylab("CH4 flux")

d4 <- ggplot(CH4_day, aes(x = avg_respT, y = flux.CH4))+
  geom_point()+
  geom_smooth()+
  theme_classic()+
  theme(legend.position="none")+
  facet_wrap(~species, scales = "free")+
  xlab("Temperature (C)")+
  ylab("CH4 flux")

ggarrange(d3, d4)
```
