---
title: "7.flux_viz"
author: "abbey yatsko"
date: "26/08/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(dplyr)
library(plyr)
library(ggpubr)
```

data load 
```{r}
# all fluxes - mound 
all_fluxes_mound <- read.csv("/Users/abbeyyatsko/Desktop/repos/TMI_flux/data/finalfluxes/all_fluxes_mound.csv")
# all fluxes - mound average
all_fluxes_mound_avg <- read.csv("/Users/abbeyyatsko/Desktop/repos/TMI_flux/data/finalfluxes/all_fluxes_mound_avg.csv")
# all fluxes - seasonal with replication, as a mound average
all_fluxes_seasonal_avg <- read.csv("/Users/abbeyyatsko/Desktop/repos/TMI_flux/data/finalfluxes/all_fluxes_resample_reps_avg.csv")
# all fluxes - daily 
all_fluxes_daily <- read.csv("/Users/abbeyyatsko/Desktop/repos/TMI_flux/data/finalfluxes/all_daily_fluxes.csv")
# all fluxes - naked termites 
all_fluxes_NT <- read.csv("/Users/abbeyyatsko/Desktop/repos/TMI_flux/data/finalfluxes/all_fluxes_NT.csv")
```

mound flux and species
```{r}
# average mound CH4 flux from three different species
m1 <- ggplot(data = all_fluxes_mound_avg, aes(x = species_s, y = mean_mound_fluxCH4, fill = species_s)) + 
  geom_boxplot()+ 
  scale_x_discrete(limits = c("N. magnus", "A. laurensis", "C. acinaciformis"))+  
  theme_classic()+
  ylim(0,28000) + # removes two outliers to make graph more readable
  ylab("CH4 flux umol/d/m2")+
  xlab("")

# average mound CO2 flux from three different species
m2 <- ggplot(data = all_fluxes_mound_avg, aes(x = species_s, y = mean_mound_fluxCO2, fill = species_s)) + 
  geom_boxplot()+ 
  scale_x_discrete(limits = c("N. magnus", "A. laurensis", "C. acinaciformis"))+  
  theme_classic()+
  ylab("CO2 flux mmol/d/m2")+
  xlab("")

# overall CH4:CO2 from three different species
m3 <- ggplot(data = all_fluxes_mound_avg, aes(x = species_s, y = mean_mound_fluxCH4_CO2, fill = species_s)) + 
  geom_boxplot()+ 
  scale_x_discrete(limits = c("N. magnus", "A. laurensis", "C. acinaciformis"))+  
  theme_classic()+
  ylab("CH4:CO2")+
  ylim(0,0.04)+ # removes big outlier
  xlab("")

ggarrange(m1,m2,m3, ncol = 3, common.legend = TRUE)

# table of averages by species
detach(package:plyr)
sp_avg <- all_fluxes_mound_avg %>% group_by(species_s) %>% 
  summarize(mean_CH4flux = mean(mean_mound_fluxCH4), 
            mean_CO2flux = mean(mean_mound_fluxCO2), 
            sd_CH4flux = sd(mean_mound_fluxCH4), 
            sd_CO2flux = sd(mean_mound_fluxCO2))
  
# unit conversion umol/m2*d to ug/m2*d (final units for CH4)
# flux*(1/1000000)*(16.04)*(1000000) 
# molecular mass conversion to g, then conversion back to ug for comparison 
```

mound flux and season
```{r}
# reorder levels of campaigns 
all_fluxes_mound_avg$campaign <- factor(all_fluxes_mound_avg$campaign, levels = c("may22", "aug23", "nov22", "feb24"))

# CH4 flux 
s1 <- ggplot(all_fluxes_mound_avg, aes(x = species_s, y = mean_mound_fluxCH4, fill = campaign)) + 
  geom_boxplot()+ 
  scale_x_discrete(limits = c("N. magnus", "A. laurensis", "C. acinaciformis"))+  
  theme_classic()+
  ylim(0, 22186) + # removes negative outlier
  ylab("CH4 flux umol/d/m2")+
  xlab("")+
  scale_fill_viridis_d(option = "plasma")+
  theme(legend.position = "none")

# CO2 flux 
s2 <- ggplot(data = all_fluxes_mound_avg, aes(x = species_s, y = mean_mound_fluxCO2, fill = campaign))+
  geom_boxplot()+ 
  scale_x_discrete(limits = c("N. magnus", "A. laurensis", "C. acinaciformis"))+  
  theme_classic()+
  ylab("CO2 flux mmol/d/m2")+
  xlab("")+
  scale_fill_viridis_d(option = "plasma")+
  theme(legend.position = "bottom")

# overall CH4:CO2 from three different species
s3 <- ggplot(data = all_fluxes_seasonal_avg, aes(x = species_s, y = mean_mound_fluxCH4_CO2, fill = campaign)) + 
  geom_boxplot()+ 
  scale_x_discrete(limits = c("N. magnus", "A. laurensis", "C. acinaciformis"))+  
  theme_classic()+
  ylab("CH4:CO2")+
  ylim(0,0.06)+ # removes big outlier
  xlab("")

s1 + s2 + plot_layout(ncol = 1)+ patchwork::plot_annotation(tag_levels = "a")
```

mound flux and temperature
```{r}
# mound flux and temperature
t1 <- ggplot(all_fluxes_mound_avg, aes(x = temp, y = mean_mound_fluxCH4, color = species_s))+
  geom_smooth(method = 'lm', se = TRUE)+
  geom_point()+
  ylab("CH4 flux umol/d/m2")+
  xlab("Average Mound Surface Temperature (C)")+
  theme_classic()

t2 <- ggplot(all_fluxes_mound_avg, aes(x = temp, y = mean_mound_fluxCO2, color = species_s))+
  geom_smooth(method = 'lm', se = TRUE)+
  geom_point()+
  ylab("CO2 flux mmol/d/m2")+
  xlab("Average Mound Surface Temperature (C)")+
  theme_classic()

ggarrange(t1, t2, ncol = 1, common.legend = TRUE)

# mound flux and time of day with temperature included
all_fluxes_seasonal_mound <- all_fluxes_seasonal[all_fluxes_seasonal$flux_source == "m",]
t <- all_fluxes_seasonal_mound[all_fluxes_seasonal_mound$campaign %in% c("nov22", "aug23", "feb24"),]
t$flux_start <- strptime(t$flux_start, "%H:%M")

tt <- all_fluxes_seasonal_mound[all_fluxes_seasonal_mound$campaign %in% c("may22"),]
start <- nchar(tt$flux_start) - 7
tt$flux_start_test <- substring(tt$flux_start, start, nchar(tt$flux_start))
tt$flux_start <- strptime(tt$flux_start_test, "%H:%M")
tt <- tt[, -which(names(tt) == "flux_start_test")]

all_fluxes_seasonal_mound_withtime <- rbind(t, tt)

# temperature throughout the day by season
t3 <- ggplot(all_fluxes_seasonal_mound_withtime, aes(x = as.POSIXct(flux_start), y = avg_respT, color = campaign))+
  geom_jitter()+
  geom_smooth(method = 'lm', se = TRUE)+
  ylab("Average Mound Surface Temperature (C)")+
  xlab("Time of day")+
  theme_classic()

# temperature response of gas flux by season
t4 <- ggplot(all_fluxes_seasonal_mound_withtime, aes(x = avg_respT, y = flux.CH4, color = campaign))+
  geom_point()+
  geom_smooth(method = 'lm', se = FALSE)+
  ylab("CH4 flux umol/d/m2")+
  xlab("Average Mound Surface Temperature (C)")+
  theme_classic()+
  ylim(0,25000) # address negative outlier 

ggarrange(t3, t4, ncol = 1, common.legend = TRUE)

# table of averages by season (all mounds, not those with repeat measurements)
detach(package:plyr)
season_avg <- all_fluxes_mound_avg %>% group_by(species_s, campaign) %>% 
  summarize(mean_CH4flux = mean(mean_mound_fluxCH4), 
            mean_CO2flux = mean(mean_mound_fluxCO2), 
            sd_CH4flux = sd(mean_mound_fluxCH4), 
            sd_CO2flux = sd(mean_mound_fluxCO2), 
            count = n())
# EXPORT
# write.csv(season_avg, "/Users/abbeyyatsko/Desktop/repos/TMI_flux/data/data_out/season_avg.csv", row.names = FALSE)
```

mound flux and position
```{r}
# position in mound
all_fluxes_mound$position <- ifelse(all_fluxes_mound$position == "top ", "top", all_fluxes_mound$position)
ggplot(data = all_fluxes_mound, aes(x = species_s, y = flux.CH4, fill = position)) + 
  geom_boxplot()+ 
  theme_classic()+
  ylab("CH4 flux umol/d/m2")+
  ylim(0,24000)+ # removes big outlier
  xlab("")

# direction on mound
ggplot(data = all_fluxes_mound, aes(x = directon, y = flux.CH4, fill = directon)) + 
  geom_boxplot()+ 
  theme_classic()+
  ylab("CH4 flux umol/d/m2")+
  ylim(0,24000)+ # removes big outlier
  xlab("Direction")+
  scale_x_discrete(limits = c("E", "N", "S", "W"), labels = c("E", "N", "S", "W"))
```

mound flux and size
```{r}
# reorder levels of campaigns 
all_fluxes_mound_avg$campaign <- factor(all_fluxes_mound_avg$campaign, levels = c("may22", "aug23", "nov22", "feb24"))
# graph methane flux by mound size (surface/basal area interchangeable: SA_m2/basal_area_m2)
a1 <- ggplot(all_fluxes_mound_avg, aes(x = SA_m2, y = mean_mound_fluxCH4)) +
  geom_point()+ 
  geom_smooth(method = 'lm')+
  facet_wrap(species_s~campaign, scales = "free")+ 
  theme_classic()+
  ylab("Mean mound CH4 flux (umol/d/mound)") +
  xlab("Mound surface area (m2)")

# graph carbon dioxide flux by mound size 
a2 <- ggplot(data = all_fluxes_mound_avg, aes(x = SA_m2, y = mean_mound_fluxCO2)) +
  geom_point()+ 
  geom_smooth(method = 'lm')+
  facet_grid(species_s~campaign, scales = "free_x")+ 
  theme_classic()+
  ylab("Total mound CO2 flux (mmol/d/mound)") +
  xlab("Mound surface area (m2)")

# graph CH4:CO2 flux by mound size 
a3 <- ggplot(data = all_fluxes_mound_avg, aes(x = SA_m2, y = mean_mound_fluxCH4_CO2)) +
  geom_point()+ 
  geom_smooth(method = 'lm')+
  scale_color_brewer("Blues")+
  facet_wrap(~species_s, scales = "free_x")+ 
  theme_classic()+
  ylab("Total mound CH4:CO2") +
  xlab("Mound basal area (m2)")

ggarrange(a1, a2, ncol = 1)

# relationship between surface area and basal area (by species)
ggplot(all_fluxes_mound_avg, aes(x = SA_m2, y = basal_area_m2)) +
  geom_point()+ 
  geom_smooth(method = 'lm')+
  scale_color_brewer("Blues")+
  facet_wrap(~species_s, scales = "free_x")+ 
  theme_classic()+
  ylab("Mound basal area (m2)") +
  xlab("Mound surface area (m2)")
```

mound flux and wall thickness 
```{r}
wt <- all_fluxes_mound[!is.na(all_fluxes_mound$wall_thickness_mm), ]

w1 <- ggplot(wt, aes(x = wall_thickness_mm, y = flux.CH4, color = species_s)) +
  geom_point()+ 
  geom_smooth(method = "lm")+
  theme_classic()+
  ylab("CH4 flux umol/d/m2")+
  xlab("Mound wall thickness (mm)")+
  ggtitle("Sample point wall thickness")+
  theme(legend.position = "none")

# calculate average mound wall thickness
wt_avg <- wt %>% group_by(ID_mound, sample, species_s) %>% 
  summarise(mean_mound_fluxCH4=mean(flux.CH4),
            mean_mound_fluxCO2=mean(flux.CO2_umol), 
            mean_mound_fluxCH4_CO2=mean(CH4_CO2), 
            campaign = campaign, 
            temp = mean(avg_respT), 
            precip_1mo = precip_1mo, 
            precip_2mo = precip_2mo, 
            precip_3mo = precip_3mo,
            wall_thickness_mm = mean(wall_thickness_mm))
wt_mound_avg <- distinct(wt_avg)

w2 <- ggplot(wt_mound_avg, aes(x = wall_thickness_mm, y = mean_mound_fluxCH4, color = species_s)) +
  geom_point()+ 
  geom_smooth(method = "lm")+
  theme_classic()+
  ylab("CH4 flux umol/d/m2")+
  xlab("Mound wall thickness (mm)")+
  ggtitle("Average mound wall thickness")+
  theme(legend.position = "bottom")

w1 + w2 + plot_layout(ncol = 1)+ patchwork::plot_annotation(tag_levels = "a")
```

mound flux throughout the day
```{r}
# reorder levels of time of day
all_fluxes_daily$time_of_day <- factor(all_fluxes_daily$time_of_day, levels = c("morning", "midday", "afternoon", "night"))

# time by flux for species
ggplot(all_fluxes_daily, aes(x = species_s, y = flux.CH4, fill = time_of_day))+
  geom_boxplot()+
  theme_classic()+
  xlab("")+
  ylab("CH4 flux (umol/d/mound)")+
  ylim(0,25000) # removes outlier

# temp by flux for species
ggplot(all_fluxes_daily, aes(x = avg_respT, y = flux.CH4, color = time_of_day))+
  geom_point()+
  geom_smooth(method = "lm")+
  facet_wrap(~species_s, scales = "free_y")+
  theme_classic()+
  xlab("Temperature (C)")+
  ylab("CH4 flux (umol/d/mound)")

# calculate mound average for flux and temp 
all_fluxes_daily$sampleTOD <- paste(all_fluxes_daily$sample, all_fluxes_daily$time_of_day, sep = "-")
daily_avg <- all_fluxes_daily %>% group_by(sampleTOD) %>% 
  summarise(mean_mound_fluxCH4=mean(flux.CH4),
            mean_mound_fluxCO2=mean(flux.CO2_umol), 
            mean_mound_fluxCH4_CO2=mean(CH4_CO2), 
            time_of_day = time_of_day, 
            species_s = species_s, 
            temp = mean(avg_respT))
daily_avg_f <- distinct(daily_avg)

# temp by flux for species at mound-level average
ggplot(daily_avg_f, aes(x = temp, y = mean_mound_fluxCH4, color = species_s))+
  geom_point()+
  geom_smooth(method = "lm")+
  #facet_wrap(~species_s, scales = "free_y")+
  theme_classic()+
  xlab("Temperature (C)")+
  ylab("CH4 flux (umol/d/mound)")

# look at individual regressions for each species
mod <- lm(mean_mound_fluxCH4 ~ temp, data = daily_avg_f[daily_avg_f$species_s == "C. acinaciformis", ])
summary(mod)

# temperature throughout daily cycle 
all_fluxes_daily$flux_start_test <- strptime(all_fluxes_daily$flux_start, "%H:%M")
ggplot(all_fluxes_daily, aes(x = as.POSIXct(flux_start_test), y = avg_respT))+
  geom_point()+
  theme_classic()+
  theme(legend.position="none")+ 
  xlab("Time of Day")+
  ylab("Temperature (C)")

# calculate Q10 (for each species) 

# define linear relationship 
ami_mod <- lm(mean_mound_fluxCH4 ~ temp, data = daily_avg_f[daily_avg_f$species_s == "A. laurensis", ])
coefficients <- coef(ami_mod)
paste("Amitermes CH4 flux =", round(coefficients[1], 2), "+", round(coefficients[2], 2), "* Temperature")
cop_mod <- lm(mean_mound_fluxCH4 ~ temp, data = daily_avg_f[daily_avg_f$species_s == "C. acinaciformis", ])
coefficients <- coef(cop_mod)
paste("Coptotermes CH4 flux =", round(coefficients[1], 2), "+", round(coefficients[2], 2), "* Temperature")
nas_mod <- lm(mean_mound_fluxCH4 ~ temp, data = daily_avg_f[daily_avg_f$species_s == "N. magnus", ])
coefficients <- coef(nas_mod)
paste("Nasutitermes CH4 flux =", round(coefficients[1], 2), "+", round(coefficients[2], 2), "* Temperature")

# define 10C difference for process
temp_low <- 20
temp_high <- 30
rate_low_temp <- 9072.65 + -66.76 * temp_low
rate_high_temp <- 9072.65 + -66.76 * temp_high

# Q10 function
calculate_Q10 <- function(rate_low_temp, rate_high_temp, temp_low, temp_high) {
  Q10 <- (rate_high_temp / rate_low_temp) ^ (10 / (temp_high - temp_low))
  return(Q10)
}

Q10_ami <- calculate_Q10(rate_low_temp, rate_high_temp, temp_low, temp_high)
Q10_cop <- calculate_Q10(rate_low_temp, rate_high_temp, temp_low, temp_high)
Q10_nas <- calculate_Q10(rate_low_temp, rate_high_temp, temp_low, temp_high)
```

naked termites 
```{r}
# termite emission factor
tef <- ggplot(all_fluxes_NT, aes(x = species, y = emission_factor, fill = species))+
  geom_boxplot()+
  geom_jitter()+
  ylab("Termite EF (umol CH4/d/g termite)")+
  xlab("")+
  scale_x_discrete(labels = c("A. laurensis", "C. acinaciformis", "N. magnus"))+
  theme_classic()+
  theme(legend.position = "none")

# flux by material 
mat_ch4 <- ggplot(all_fluxes_NT, aes(x = species, y = flux.CH4, fill = material))+
  geom_boxplot()+
  ylab("CH4 flux")+
  xlab("")+
  scale_x_discrete(labels = c("A. laurensis", "C. acinaciformis", "N. magnus"))+
  theme_classic()

mat_co2 <- ggplot(all_fluxes_NT, aes(x = species, y = flux.CO2, fill = material))+
  geom_boxplot()+
  ylab("CO2 flux")+
  xlab("")+
  scale_x_discrete(labels = c("A. laurensis", "C. acinaciformis", "N. magnus"))+
  theme_classic()

ggarrange(tef, mat_ch4, mat_co2, ncol = 1 )
```
