---
title: "8.flux_models"
author: "abbey yatsko"
date: "2024-03-15"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

libraries
```{r}
library(ggplot2)
library(lme4)
```

data load 
```{r}
all_fluxes_mound <- read.csv("/Users/abbeyyatsko/Desktop/repos/TMI_flux/data/finalfluxes/all_fluxes_mound.csv")
all_fluxes_resample_reps_avg <- read.csv("/Users/abbeyyatsko/Desktop/repos/TMI_flux/data/finalfluxes/all_fluxes_resample_reps_avg.csv")
all_fluxes_daily <- read.csv("/Users/abbeyyatsko/Desktop/repos/TMI_flux/data/finalfluxes/all_daily_fluxes.csv")
```

Test 1: intramound variation
```{r}
all_fluxes_mound$tag <- as.factor(all_fluxes_mound$tag) 
all_fluxes_mound$position <- ifelse(all_fluxes_mound$position == "top ", "top", all_fluxes_mound$position)
all_fluxes_mound$position <- as.factor(all_fluxes_mound$position) 

mod1 <- aov(flux.CH4 ~ tag + species_s, data = all_fluxes_mound)
summary(mod1)
ggpredict(mod1, terms = c("tag", "species_s")) %>% plot(add.data = TRUE)
# significant model, but add random effect of mound individual? 

mod2 <- aov(flux.CH4 ~ position + species_s, data = all_fluxes_mound)
summary(mod2)
ggpredict(mod2, terms = c("position", "species_s")) %>% plot(add.data = TRUE)
# not significant, position on the mound does not matter

# Fit linear mixed-effects model (which I think is best?)
mod3 <- lmer(flux.CH4 ~ tag + species_s + (1 | ID_mound), data = all_fluxes_mound)
anova(mod3)
check_model(mod3)
ggpredict(mod3, terms = c("tag", "species_s")) %>% plot(add.data = TRUE)
# no significant effect of tag with random effect included
```

Mound-level CoV 
```{r}
# calculate CoV for each mound
detach(package:plyr)
cov <- all_fluxes_mound %>% group_by(ID_mound) %>% 
  summarize(mean = mean(flux.CH4), 
            sd = sd(flux.CH4),
            cov = sd(flux.CH4) / mean(flux.CH4))

# plot mean, sd, and cov
mean <- ggplot(cov, aes(mean)) +
  geom_histogram(aes(y=after_stat(density)), colour="black", fill="white")+
  geom_density(alpha=.2, fill="#FF6666") +
  theme_classic()
sd <- ggplot(cov, aes(sd)) +
  geom_histogram(aes(y=after_stat(density)), colour="black", fill="white")+
  geom_density(alpha=.2, fill="#FF6666") +
  theme_classic()
cov_p <- ggplot(cov, aes(cov)) +
  geom_histogram(aes(y=after_stat(density)), colour="black", fill="white")+
  geom_density(alpha=.2, fill="#FF6666") +
  theme_classic()
ggarrange(mean, sd, cov_p, ncol = 1)

# how many mounds have high COV values?
x <- cov[cov$cov > 1, ] # cov = 1 means that sd = mean 

# if intramound variation is not significant - calculate overall mound average and use this in further analyses
```

influences of mound flux (average) for mounds that were measured in all 4 time points
species, season, temperature, size
```{r}
# Fit linear mixed-effects model
all_fluxes_resample_reps_avg$species_s <- as.factor(all_fluxes_resample_reps_avg$species_s)
all_fluxes_resample_reps_avg$campaign <- as.factor(all_fluxes_resample_reps_avg$campaign)
all_fluxes_resample_reps_avg$sample <- as.factor(all_fluxes_resample_reps_avg$sample)

# big model with them all in 
mod4 <- lmer(mean_mound_fluxCH4 ~ species_s + temp + SA_m2 + (1 | sample) + (1|campaign), data = all_fluxes_resample_reps_avg)
Anova(mod4)
check_model(mod4)
ggpredict(mod4, terms = c("temp", "species_s")) %>% plot(add.data = TRUE)

# SA and species arent important - remove SA and see what happens (consider species_s*SA_m2, but not significant, remove SA)
mod5 <- lmer(mean_mound_fluxCH4 ~ species_s  + temp + (1 | sample) + (1|campaign), data = all_fluxes_resample_reps_avg)
Anova(mod5)
summary(mod5)
check_model(mod5)
ggpredict(mod5, terms = c( "campaign", "temp", "species_s")) %>% plot(add.data = TRUE)
AIC(mod4, mod5)

# visualize relationship between mound size and species 
ggplot(all_fluxes_resample_reps_avg, aes(x = species_s, y = SA_m2, fill = species_s))+
  geom_boxplot()+
  theme_classic()

# consider potential interaction between campaign and temperature
mod6 <- lmer(mean_mound_fluxCH4 ~ species_s + campaign*temp + (1 | sample), data = all_fluxes_resample_reps_avg)
anova(mod6)
check_model(mod6) # doesnt look like there is much here

# flux and te
```

does mound flux change throughout the day 
```{r}
# first test the effect of intramound variation to see if values can be averaged
all_fluxes_daily$tag <- as.factor(all_fluxes_daily$tag)
all_fluxes_daily$species_s <- as.factor(all_fluxes_daily$species_s)

mod7 <- lmer(flux.CH4 ~ tag + species_s + (1 | sample), data = all_fluxes_daily)
anova(mod7)
check_model(mod7)
ggpredict(mod7, terms = c("tag", "species_s")) %>% plot(add.data = TRUE)
# doesn't matter - generate mound-level averages and then test the effect of time of day 

# generate mound level averages for daily measurement df
all_fluxes_daily$ID_mound <- paste(all_fluxes_daily$sample, all_fluxes_daily$time_of_day, sep = "-")

all_fluxes_daily_avg <- all_fluxes_daily %>% group_by(ID_mound, sample, species_s) %>% 
  summarise(mean_mound_fluxCH4=mean(flux.CH4),
            mean_mound_fluxCO2=mean(flux.CO2_umol), 
            mean_mound_fluxCH4_CO2=mean(CH4_CO2), 
            time_of_day = time_of_day, 
            temp = mean(avg_respT))
all_fluxes_daily_avg <- distinct(all_fluxes_daily_avg)

# model 
mod8 <- lmer(mean_mound_fluxCH4 ~ species_s + time_of_day + temp + (1 | sample), data = all_fluxes_daily_avg)
anova(mod8)
check_model(mod8)
ggpredict(mod8, terms = c( "time_of_day", "temp", "species_s")) %>% plot(add.data = TRUE)

# high collinearity between time of day and temperature - maybe include interaction? 
```

mound flux and wall thickness 
```{r}
df <- all_fluxes_mound[!is.na(all_fluxes_mound$wall_thickness_mm), ]
mod <- lm(flux.CH4 ~ wall_thickness_mm, data = df)
summary(mod)
check_model(mod)
ggpredict(mod, terms = c("wall_thickness_mm")) %>% plot(add.data = TRUE)
```

#################
DRAFT DRAFT DRAFT 
#################

Variance partitioning 
```{r}
# what variables may matter: species, campaign, temperature, intramound position, hour of measurement, individual mound?
# restructure factor variables
all_fluxes_resample$species_s <- as.factor(all_fluxes_resample$species_s) 
all_fluxes_resample$campaign <- as.factor(all_fluxes_resample$campaign)
all_fluxes_resample$tag <- as.factor(all_fluxes_resample$tag)
all_fluxes_resample$sample <- as.factor(all_fluxes_resample$sample)

# extract hour of measurement from flux_start column 
h <- all_fluxes_resample$flux_start
i <- sub("\\:.*", "", h)
j <- i[121:344]
k <- i[1:120]
l <- str_sub(k, -2)
hours <- c(l,j)
all_fluxes_resample$hour <- hours
all_fluxes_resample <- all_fluxes_resample %>% relocate(hour, .after = flux_start)
all_fluxes_resample$hour <- as.numeric(all_fluxes_resample$hour)

# reasonable model, main variables of interest
vp <- varpart(all_fluxes_resample$flux.CH4, ~ avg_respT, ~ campaign, ~ species_s, data = all_fluxes_resample)
plot(vp, Xnames = c("Temp", "Campaign", "Species"), bg = c("seagreen3", "mediumpurple", "yellow"), alpha = 80, 
     digits = 2, cex = 1.5)

# model hierarchy (kelsey paper) 
# for within mound (sub measurements, temp?, position) - how much does it matter for intramound measures?
# within species (sample, temp?)
# between species (temp, campaign, time of day)

# random testing 
vp <- varpart(all_fluxes_resample$flux.CH4, ~ species_s, ~ avg_respT, ~ hour, data = all_fluxes_resample)
plot(vp, Xnames = c("Species", "Campaign", "Flux start"), bg = c("seagreen3", "mediumpurple", "yellow"), alpha = 80, 
     digits = 2, cex = 1.5)

# what parts of the partitioning are significant?
# test for significance of three influential factors using RDA
rda <- rda(all_fluxes_resample$flux.CH4~avg_respT+campaign+species_s, data=all_fluxes_resample)
rda
step.forward <- ordistep(rda(all_fluxes_resample$flux.CH4 ~ 1, data=all_fluxes_resample), scope=formula (rda), direction="forward", pstep=1000)

# temporal factors / environmental factors run seperately? 

# new package: POV
library("POV")

# level 1: within mound variation - does position matter? 
POV(flux.CH4 ~ ID_mound, Data = all_fluxes_resample, Complete=TRUE)
# Within ID_mound > Between ID_mound means that mound subsamples do matter? 

POV(flux.CH4 ~ ID_mound*position, Data = all_fluxes_resample, Complete=TRUE)
# variation across mounds is more important than the variation within mounds? 

# level 2: within species variation - does individual matter? 
POV(flux.CH4 ~ species_s*ID_mound, Data = all_fluxes_resample, Complete=TRUE)

# level 3: across species variation - do other environmental/time factors matter?
POV(flux.CH4 ~ campaign*ID_mound, Data = all_fluxes_resample, Complete=TRUE)

```

