---
title: "6.prelim_viz"
author: "abbey yatsko"
date: "26/08/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(dplyr)
library(plyr)
library(ggpubr)
library(viridis)
library(tidyr)
library(broom)
library(purrr)
library(tidyverse)
library(rstatix)
library(easystats)
library(ggeffects)
library(lme4)
library(lmerTest)
library(vegan)
```

read in data 
```{r data load}
may_CO2 <- read.csv("/Users/abbeyyatsko/Desktop/repos/TMI_flux/data/finalfluxes/CO2_fluxfinal_may22_fixed.csv")
may_CH4 <- read.csv("/Users/abbeyyatsko/Desktop/repos/TMI_flux/data/finalfluxes/CH4_fluxfinal_may22_fixed.csv")

nov_CO2 <- read.csv("/Users/abbeyyatsko/Desktop/repos/TMI_flux/data/finalfluxes/CO2_fluxfinal_nov22_fixed.csv")
nov_CH4 <- read.csv("/Users/abbeyyatsko/Desktop/repos/TMI_flux/data/finalfluxes/CH4_fluxfinal_nov22_fixed.csv")

aug_CO2 <- read.csv("/Users/abbeyyatsko/Desktop/repos/TMI_flux/data/finalfluxes/CO2_fluxfinal_aug23_fixed.csv")
aug_CH4 <- read.csv("/Users/abbeyyatsko/Desktop/repos/TMI_flux/data/finalfluxes/CH4_fluxfinal_aug23_fixed.csv")

aug_day_CO2 <- read.csv("/Users/abbeyyatsko/Desktop/repos/TMI_flux/data/finalfluxes/CO2_fluxfinal_aug23_day_fixed.csv")
aug_day_CH4 <- read.csv("/Users/abbeyyatsko/Desktop/repos/TMI_flux/data/finalfluxes/CH4_fluxfinal_aug23_day_fixed")

feb_CO2 <- read.csv("/Users/abbeyyatsko/Desktop/repos/TMI_flux/data/finalfluxes/CO2_fluxfinal_feb24.csv")
feb_CH4 <- read.csv("/Users/abbeyyatsko/Desktop/repos/TMI_flux/data/finalfluxes/CH4_fluxfinal_feb24.csv")
```

data clean and reorganize
```{r}
# lists of CO2 and CH4 files from different seasons
CH4_all <- list(may_CH4, nov_CH4, aug_CH4, feb_CH4)
CO2_all <- list(may_CO2, nov_CO2, aug_CO2, feb_CO2)

# create new column for methane:co2
# for each element in list 
x <- data.frame(CO2_all[1])
y <- data.frame(CH4_all[1])

full_df <- function(x, y){
  # merge CO2 and CH4 df together 
  all <- full_join(x, y)

  # convert CO2 from mmol to umol (in order to match CH4 units, conversion factor 1000umol = 1mmol)
  all$flux.CO2_umol <- all$flux.CO2*1000
  all <- all %>% relocate(flux.CO2_umol, .after = flux.CO2)
  all <- all %>% relocate(flux.CH4, .after = flux.CO2_umol)
  all <- all %>% relocate(R2.CH4, .after = R2.CO2)
  all <- all %>% relocate(p.CH4, .after = p.CO2)
  
  # define column for ratio of CH4:CO2
  all$CH4_CO2 <-  all$flux.CH4/all$flux.CO2_umol
  all <- all %>% relocate(CH4_CO2, .after = flux.CH4)

}

out <- lapply(seq_along(CH4_all), function(x) full_df(CH4_all[[x]], CO2_all[[x]]))
all_fluxes <- do.call("rbind.fill", out)

# rename species with scientific names 
all_fluxes$species_s <- ifelse(all_fluxes$species == "Ami", "A. laurensis","")
all_fluxes$species_s <- ifelse(all_fluxes$species == "Nasuti", "N. magnus", all_fluxes$species_s)
all_fluxes$species_s <- ifelse(all_fluxes$species == "Copto", "C. acinaciformis", all_fluxes$species_s)

# filter out measurements without species recorded
all_fluxes <- all_fluxes %>%
  filter(species_s != "")

# write.csv(all_fluxes, "/Users/abbeyyatsko/Desktop/repos/TMI_flux/data/finalfluxes/all_fluxes.csv")

# summary of how mounds were measured for each campaign
detach(package:plyr)
summary_counts <- all_fluxes %>%
  group_by(campaign, species_s) %>%
    summarise(unique_samples = n_distinct(sample))

# how many measurements were made for each mound in the resampling campaign (shoudl be 4 or 5)
# filter out those that are not revisited by the resampling campaigns 
targets1 <- unique(nov_CH4$sample)
targets2 <- unique(aug_CH4$sample)
targets3 <- unique(feb_CH4$sample)
targets <- union(targets1, targets2)
targets_fin <- union(targets, targets3)

all_fluxes_resample <- all_fluxes[all_fluxes$sample %in% targets_fin, ]

# omit soil measurements cause they're not needed right now
all_fluxes_resample <- all_fluxes_resample[all_fluxes_resample$flux_source =="m",]
all_fluxes_resample$tag <- as.factor(all_fluxes_resample$tag)

# create unique ID for mounds in different sampling periods
all_fluxes_resample$ID_mound <- paste(all_fluxes_resample$sample, all_fluxes_resample$campaign, sep = "-")

# measurements per mound 
measurements_per_mound <- aggregate(all_fluxes_resample$tag , by=list(all_fluxes_resample$ID_mound ), FUN=length)

# measurements across all 4 campaigns 
repeated_counts <- all_fluxes_resample %>%
  group_by(sample) %>%
    summarise(remeasurements = n_distinct(campaign), 
              species = unique(species_s))

# reorder levels of campaigns 
all_fluxes_resample$campaign <- factor(all_fluxes_resample$campaign, levels = c("may22", "aug23", "nov22", "feb24"))

# create working df for coarse mound averages 
mound_avg_flux <- all_fluxes_resample %>% group_by(ID_mound, sample, species_s) %>% 
  summarise(mean_mound_fluxCH4=mean(flux.CH4),
            mean_mound_fluxCO2=mean(flux.CO2_umol), 
            mean_mound_fluxCH4_CO2=mean(CH4_CO2), 
            campaign = campaign)
```

average mound flux by species and season 
```{r}
# overall CH4 flux from three different species
s1 <- ggplot(data = all_fluxes, aes(x = species_s, y = flux.CH4, fill = campaign)) + 
  geom_boxplot()+ 
  scale_x_discrete(limits = c("N. magnus", "A. laurensis", "C. acinaciformis"))+  
  theme_classic()+
  ylab("CH4 flux umol/d/m2")+
  xlab("")

# overall CO2 flux from three different species
s2 <- ggplot(data = all_fluxes, aes(x = species_s, y = flux.CO2, fill = campaign)) + 
  geom_boxplot()+ 
  scale_x_discrete(limits = c("N. magnus", "A. laurensis", "C. acinaciformis"))+  
  theme_classic()+
  ylab("CO2 flux mmol/d/m2")+
  xlab("")

# overall CH4:CO2 from three different species
s3 <- ggplot(data = all_fluxes, aes(x = species_s, y = CH4_CO2, fill = species_s)) + 
  geom_boxplot()+ 
  scale_x_discrete(limits = c("N. magnus", "A. laurensis", "C. acinaciformis"))+  
  theme_classic()+
  ylab("CH4:CO2")+
  ylim(0,0.075)+ # removes big outlier
  xlab("")

ggarrange(s1,s2,s3, ncol = 3)

# table of averages (by species, season)
detach(package:plyr)
sp_avg <- all_fluxes %>% group_by(species_s) %>% 
  summarize(mean_CH4flux = mean(flux.CH4), 
            mean_CO2flux = mean(flux.CO2), 
            sd_CH4flux = sd(flux.CH4), 
            sd_CO2flux = sd(flux.CO2))

season_avg <- all_fluxes %>% group_by(species_s, campaign) %>% 
  summarize(mean_CH4flux = mean(flux.CH4), 
            mean_CO2flux = mean(flux.CO2), 
            sd_CH4flux = sd(flux.CH4), 
            sd_CO2flux = sd(flux.CO2))
  
# unit conversion umol/m2*d to ug/m2*d (final units for CH4)
# flux*(1/1000000)*(16.04)*(1000000) 
# molecular mass conversion to g, then conversion back to ug for comparison 
```

Temperature relationships
```{r}
# mound flux and temperature
t1 <- ggplot(all_fluxes, aes(x = avg_respT, y = flux.CH4, color = campaign))+
  geom_point()+
  facet_wrap(~species_s)+
  geom_smooth(method = 'lm', se = FALSE, color = "red")+
  ylab("CH4 flux umol/d/m2")+
  xlab("Average Mound Surface Temperature (C)")+
  ylim(0,26000)+
  theme_classic()

t2 <- ggplot(all_fluxes, aes(x = avg_respT, y = flux.CO2, color = campaign))+
  geom_point()+
  facet_wrap(~species_s)+
  geom_smooth(method = 'lm', se = FALSE, color = "red")+
  ylab("CO2 flux mmol/d/m2")+
  xlab("Average Mound Surface Temperature (C)")+
  ylim(0,5000)+
  theme_classic()

ggarrange(t1, t2, ncol = 1)

# mound flux and time of day with temperature included
t <- all_fluxes[all_fluxes$campaign %in% c("nov22", "aug23", "feb24"),]
t$flux_start <- strptime(t$flux_start, "%H:%M")
tt <- all_fluxes[all_fluxes$campaign %in% c("may22"),]
time_all_fluxes <- rbind(t, tt)

t3 <- ggplot(time_all_fluxes, aes(x = as.POSIXct(flux_start), y = flux.CH4, color = avg_respT))+
  geom_point()+
  facet_wrap(~campaign, scales = "free_x")+
  geom_smooth(method = 'lm', se = FALSE, color = "red")+
  ylab("CH4 flux umol/d/m2")+
  xlab("Time of day")+
  scale_color_viridis(option="magma")+
  theme_classic()+
  ylim(0,30000) 

t4 <- ggplot(time_all_fluxes, aes(x = as.POSIXct(flux_start), y = flux.CO2, color = avg_respT))+
  geom_point()+
  facet_wrap(~campaign, scales = "free_x")+
  geom_smooth(method = 'lm', se = FALSE, color = "red")+
  ylab("CO2 flux mmol/d/m2")+
  xlab("Time of day")+
  scale_color_viridis(option="magma")+
  theme_classic()
  #ylim(0,30000) 
ggarrange(t3, t4, ncol = 1, common.legend = TRUE)

# temperature throughout the day
ggplot(time_all_fluxes, aes(x = as.POSIXct(flux_start), y = avg_respT, color = avg_respT))+
  geom_point()+
  facet_wrap(~campaign, scales = "free_x")+
  ylab("Average Mound Surface Temperature (C)")+
  xlab("Time of day")+
  scale_color_viridis(option="magma")+
  theme_classic()+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

```

## WORKING HERE ## 
mound flux by mound size
```{r}
# merge with mound SA
mound_SA <- read.csv("/Users/abbeyyatsko/Desktop/repos/TMI_flux/data/moundSA.csv")
mound_SA <- mound_SA[, c('sample', 'SA_m2', 'basal_area_m2')]
mound_SA <- mound_SA[!is.na(mound_SA$SA_m2),]
mound_avg_flux <- merge(mound_avg_flux, mound_SA, by = "sample" )

# calculate mound-level flux
mound_avg_flux$mound_CH4flux <- mound_avg_flux$mean_mound_fluxCH4 * mound_avg_flux$SA_m2
mound_avg_flux$mound_CO2flux <- mound_avg_flux$mean_mound_fluxCO2 * mound_avg_flux$SA_m2

# graph methane flux by mound size (surface/basal area interchangeable: SA_m2/basal_area_m2)
a1 <- ggplot(data = mound_avg_flux, aes(x = SA_m2, y = mean_mound_fluxCH4)) +
  geom_point()+ 
  geom_smooth(method = 'lm')+
  scale_color_brewer("Blues")+
  #facet_grid(~campaign, scales = "free_x")+ 
  theme_classic()+
  ylab("Total mound CH4 flux (umol/d/mound)") +
  xlab("Mound basal area (m2)")

# graph carbon dioxide flux by mound size 
a2 <- ggplot(data = mound_avg_flux, aes(x = basal_area_m2, y = mean_mound_fluxCO2)) +
  geom_point()+ 
  geom_smooth(method = 'lm')+
  scale_color_brewer("Blues")+
  facet_wrap(campaign~species_s, scales = "free_x")+ 
  theme_classic()+
  ylab("Total mound CO2 flux (mmol/d/mound)") +
  xlab("Mound basal area (m2)")

# graph CH4:CO2 flux by mound size 
a3 <- ggplot(data = mound_avg_flux, aes(x = basal_area_m2, y = mean_mound_fluxCH4_CO2)) +
  geom_point()+ 
  geom_smooth(method = 'lm')+
  scale_color_brewer("Blues")+
  facet_wrap(~species_s, scales = "free_x")+ 
  theme_classic()+
  ylab("Total mound CH4:CO2") +
  xlab("Mound basal area (m2)")

ggarrange(a1, a2, a3, ncol = 1)

# relationship between surface area and basal area (by species)
ggplot(data = mound_avg_flux, aes(x = SA_m2, y = basal_area_m2)) +
  geom_point()+ 
  geom_smooth(method = 'lm')+
  scale_color_brewer("Blues")+
  facet_wrap(~species_s, scales = "free_x")+ 
  theme_classic()+
  ylab("Mound basal area (m2)") +
  xlab("Mound surface area (m2)")

# preliminary models 
mod <- lm(mean_mound_fluxCH4 ~ SA_m2 + species_s, data = mound_avg_flux)
summary(mod)
check_model(mod)
ggpredict(mod, terms = c("SA_m2", "species_s")) %>% plot(add.data = TRUE)

```




TESTS YAY 

Intramound variation - look at mound-level CoV 
```{r}
# calculate CoV for each mound
detach(package:plyr)
cov <- all_fluxes_resample %>% group_by(ID_mound) %>% 
  summarize(cov = sd(flux.CH4) / mean(flux.CH4))
ggplot(cov, aes(cov)) +
  geom_histogram(aes(y=after_stat(density)), colour="black", fill="white")+
 geom_density(alpha=.2, fill="#FF6666") +
  theme_classic()

x <- cov[cov$cov > 1, ] # 14/75 mounds have high CoV - test these further
names <- x$ID_mound
test <- all_fluxes_resample[all_fluxes_resample$ID_mound %in% names,]

# one-way anova - using measurement tags (4-5 per mound)
ggboxplot(test, x = "tag", y = "flux.CH4",
          color = "tag", palette = c("#00AFBB", "#E7B800", "#FC4E07", "#FC4E40", "#FC9E40"),
          ylab = "Flux", xlab = "Position")
aov1 <- aov(flux.CH4 ~ tag, data = test)
summary(aov1)

# one-way anova - using position (Mid/low/top)
ggboxplot(test, x = "position", y = "flux.CH4",
          color = "position", palette = c("#00AFBB", "#E7B800", "#FC4E07"),
          ylab = "Flux", xlab = "Position")
aov2 <- aov(flux.CH4 ~ position, data = test)
summary(aov2)

# one-way anova - using direction (NESW)
ggboxplot(test, x = "directon", y = "flux.CH4",
          color = "directon", palette = c("#00AFBB", "#E7B800", "#FC4E07", "#FC4E40", "#FC9E40"),
          ylab = "Flux", xlab = "Position")
aov3 <- aov(flux.CH4 ~ directon, data = test)
summary(aov3)

# intramound variation is not significant - calculate overall mound average and use this in further analyses
```

Testing models randomly and with some difficulty
```{r}
# model with subsample position within individual mound measurement as a random effect
# CH4
model <- lmer(flux.CH4 ~ species_s + campaign + avg_respT + (1|tag), data=all_fluxes_resample, REML=TRUE)
anova(model)
rand(model)
check_model(model)
ggpredict(model, terms = c("avg_respT", "species_s", "campaign")) %>% plot(add.data = TRUE)

# CO2
model <- lmer(flux.CO2 ~ species_s + campaign + avg_respT + (1|tag), data=all_fluxes_resample, REML=TRUE)
anova(model)
rand(model)
check_model(model)
ggpredict(model, terms = c("avg_respT", "species_s", "campaign")) %>% plot(add.data = TRUE)

```

Variance partitioning 
```{r}
# what variables may matter: species, campaign, temperature, intramound position, hour of measurement, individual mound?
# restructure factor variables
all_fluxes_resample$species_s <- as.factor(all_fluxes_resample$species_s) 
all_fluxes_resample$campaign <- as.factor(all_fluxes_resample$campaign)
all_fluxes_resample$tag <- as.factor(all_fluxes_resample$tag)
all_fluxes_resample$sample <- as.factor(all_fluxes_resample$sample)

# extract hour of measurement from flux_start column 
h <- all_fluxes_resample$flux_start
i <- sub("\\:.*", "", h)
j <- i[121:344]
k <- i[1:120]
l <- str_sub(k, -2)
hours <- c(l,j)
all_fluxes_resample$hour <- hours
all_fluxes_resample <- all_fluxes_resample %>% relocate(hour, .after = flux_start)
all_fluxes_resample$hour <- as.numeric(all_fluxes_resample$hour)

# reasonable model, main variables of interest
vp <- varpart(all_fluxes_resample$flux.CH4, ~ avg_respT, ~ campaign, ~ species_s, data = all_fluxes_resample)
plot(vp, Xnames = c("Temp", "Campaign", "Species"), bg = c("seagreen3", "mediumpurple", "yellow"), alpha = 80, 
     digits = 2, cex = 1.5)

# model hierarchy (kelsey paper) 
# for within mound (sub measurements, temp?, position) - how much does it matter for intramound measures?
# within species (sample, temp?)
# between species (temp, campaign, time of day)

# random testing 
vp <- varpart(all_fluxes_resample$flux.CH4, ~ species_s, ~ avg_respT, ~ hour, data = all_fluxes_resample)
plot(vp, Xnames = c("Species", "Campaign", "Flux start"), bg = c("seagreen3", "mediumpurple", "yellow"), alpha = 80, 
     digits = 2, cex = 1.5)

# what parts of the partitioning are significant?
# test for significance of three influential factors using RDA
rda <- rda(all_fluxes_resample$flux.CH4~avg_respT+campaign+species_s, data=all_fluxes_resample)
rda
step.forward <- ordistep(rda(all_fluxes_resample$flux.CH4 ~ 1, data=all_fluxes_resample), scope=formula (rda), direction="forward", pstep=1000)

# temporal factors / environmental factors run seperately? 

# new package: POV
library("POV")

# level 1: within mound variation - does position matter? 
POV(flux.CH4 ~ ID_mound, Data = all_fluxes_resample, Complete=TRUE)
# Within ID_mound > Between ID_mound means that mound subsamples do matter? 

POV(flux.CH4 ~ ID_mound*position, Data = all_fluxes_resample, Complete=TRUE)
# variation across mounds is more important than the variation within mounds? 

# level 2: within species variation - does individual matter? 
POV(flux.CH4 ~ species_s*ID_mound, Data = all_fluxes_resample, Complete=TRUE)

# level 3: across species variation - do other environmental/time factors matter?
POV(flux.CH4 ~ campaign*ID_mound, Data = all_fluxes_resample, Complete=TRUE)

```


drivers of flux variation throughout the day
{see 5.DAILY_process.Rmd}



